# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Millenial Lifehacker
email: contact@ericreichert.com
description: > # this means to ignore newlines until "baseurl:"
  I run, I travel, and I tinker. This site was created to capture all of those moments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ericreichert.com" # the base hostname & protocol for your site
twitter_username: ericreichert
github_username:  reicherte

# Build settings
markdown: kramdown
