# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BrandAm
email: contact@BrandAm.com
description: > # this means to ignore newlines until "baseurl:"
  BrandAm is a service that allows companies to connect with their ambassadors so that they can reward and incentivize their actions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://BrandAm.co" # the base hostname & protocol for your site
twitter_username: BrandAm
github_username:  ReichertE

# Build settings
markdown: kramdown
